# Generated by Django 3.1.5 on 2021-05-14 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyBaseUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('melli_code', models.PositiveIntegerField(max_length=10, unique=True, verbose_name='کد ملی')),
                ('phone', models.PositiveIntegerField(max_length=11, unique=True, verbose_name='تلفن')),
                ('two_factor', models.PositiveIntegerField(max_length=10, unique=True, verbose_name='کد ملی')),
            ],
        ),
    ]
