# Generated by Django 3.1.5 on 2021-05-14 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EDU_signup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mybaseuser',
            name='two_factor',
            field=models.PositiveIntegerField(max_length=10, unique=True, verbose_name='کد رهگیری'),
        ),
    ]
