# Generated by Django 3.1.5 on 2021-05-14 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EDU_signup', '0002_auto_20210514_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mybaseuser',
            name='two_factor',
            field=models.PositiveIntegerField(blank=True, max_length=10, unique=True, verbose_name='کد رهگیری'),
        ),
    ]
