# Generated by Django 3.1.5 on 2021-05-14 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EDU_signup', '0003_auto_20210514_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mybaseuser',
            name='two_factor',
        ),
        migrations.AddField(
            model_name='mybaseuser',
            name='two_factor_code',
            field=models.PositiveIntegerField(blank=True, max_length=10, null=True, verbose_name='کد رهگیری'),
        ),
    ]
