# Generated by Django 3.1.5 on 2021-05-15 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EDU_signup', '0005_auto_20210514_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mybaseuser',
            name='melli_code',
            field=models.CharField(max_length=10, unique=True, verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='mybaseuser',
            name='phone',
            field=models.CharField(max_length=11, unique=True, verbose_name='تلفن'),
        ),
    ]
