# Generated by Django 3.1.5 on 2021-05-15 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EDU_signup', '0007_auto_20210515_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mybaseuser',
            name='two_factor_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='کد رهگیری'),
        ),
    ]
