# Generated by Django 3.1.5 on 2021-05-18 19:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('EDU_user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_auth_state',
            name='is_good',
        ),
        migrations.AddField(
            model_name='user_auth_state',
            name='stu_birthday',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='تاریخ تولد'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_auth_state',
            name='stu_father_name',
            field=models.CharField(default='', max_length=25, verbose_name='نام پدر'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_auth_state',
            name='stu_first_name',
            field=models.CharField(default='', max_length=25, verbose_name='نام'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_auth_state',
            name='stu_last_moadel',
            field=models.CharField(blank=True, max_length=5, verbose_name='معدل سال پیش'),
        ),
        migrations.AddField(
            model_name='user_auth_state',
            name='stu_last_name',
            field=models.CharField(default='', max_length=25, verbose_name='نام خانوادگی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_auth_state',
            name='stu_paye',
            field=models.CharField(choices=[('fourth', 'چهارم'), ('fifth', 'پنجم'), ('sixth', 'ششم')], default='', max_length=15, verbose_name='پایه مورد نظر'),
            preserve_default=False,
        ),
    ]
