# Generated by Django 3.1.5 on 2021-06-09 14:15

import EDU_user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EDU_user', '0004_auto_20210608_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_upload_files',
            name='scan_dad',
            field=models.ImageField(upload_to=EDU_user.models.media_upload_path, verbose_name='اسکن شناسنامه پدر'),
        ),
        migrations.AlterField(
            model_name='user_upload_files',
            name='scan_karname',
            field=models.ImageField(upload_to=EDU_user.models.media_upload_path, verbose_name='اسکن کارنامه آخر'),
        ),
        migrations.AlterField(
            model_name='user_upload_files',
            name='scan_lease',
            field=models.ImageField(upload_to=EDU_user.models.media_upload_path, verbose_name='اسکن سند یا قولنامه محل زندگی'),
        ),
        migrations.AlterField(
            model_name='user_upload_files',
            name='scan_mom',
            field=models.ImageField(upload_to=EDU_user.models.media_upload_path, verbose_name='اسکن شناسنامه مادر'),
        ),
        migrations.AlterField(
            model_name='user_upload_files',
            name='scan_student',
            field=models.ImageField(upload_to=EDU_user.models.media_upload_path, verbose_name='اسکن شناسنامه دانش آموز'),
        ),
    ]
